# Generated by Django 5.2.4 on 2026-08-09 12:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academics', '0001_initial'),
        ('staff', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AllocationRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('RUNNING', 'Running'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed')], default='PENDING', max_length=20)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('academic_year', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='allocation_runs', to='academics.academicyear')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AllocationConflict',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('conflict_type', models.CharField(choices=[('FACULTY_OVERLOAD', 'Faculty Overload'), ('FACULTY_UNAVAILABLE', 'Faculty Unavailable'), ('SCHEDULE_CONFLICT', 'Schedule Conflict'), ('DUPLICATE_ALLOCATION', 'Duplicate Allocation'), ('SECTION_CONFLICT', 'Section Conflict'), ('SUBJECT_CONFLICT', 'Subject Conflict'), ('NO_ELIGIBLE_FACULTY', 'No Eligible Faculty'), ('PREFERENCE_VIOLATION', 'Preference Violation')], max_length=40)),
                ('severity', models.CharField(choices=[('INFO', 'Information'), ('WARNING', 'Warning'), ('ERROR', 'Error'), ('CRITICAL', 'Critical')], default='WARNING', max_length=20)),
                ('status', models.CharField(choices=[('OPEN', 'Open'), ('RESOLVED', 'Resolved'), ('IGNORED', 'Ignored')], default='OPEN', max_length=20)),
                ('message', models.TextField()),
                ('details', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('faculty', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='allocation_conflicts', to='staff.faculty')),
                ('allocation_run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conflicts', to='allocation.allocationrun')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SubjectAllocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('PROPOSED', 'Proposed'), ('CONFIRMED', 'Confirmed'), ('REJECTED', 'Rejected'), ('MANUAL', 'Manual')], default='PROPOSED', max_length=20)),
                ('preference_score', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('workload_hours', models.PositiveSmallIntegerField(default=0)),
                ('is_preference_matched', models.BooleanField(default=False)),
                ('is_conflict_free', models.BooleanField(default=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('allocation_run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subject_allocations', to='allocation.allocationrun')),
                ('faculty', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='subject_allocations', to='staff.faculty')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='subject_allocations', to='academics.section')),
                ('subject_offering', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='allocations', to='academics.subjectoffering')),
            ],
            options={
                'ordering': ['allocation_run', 'subject_offering', 'section'],
                'unique_together': {('allocation_run', 'subject_offering', 'section')},
            },
        ),
    ]
