# Generated by Django 5.2.4 on 2026-08-05 16:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0001_initial'),
        ('preferences', '0002_facultyavailability'),
        ('staff', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PreferredSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('priority', models.PositiveSmallIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('faculty', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='preferred_sections', to='staff.faculty')),
                ('preference_cycle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='preferred_sections', to='preferences.preferencecycle')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='preferred_faculties', to='academics.section')),
            ],
            options={
                'ordering': ['faculty', 'priority'],
                'unique_together': {('faculty', 'preference_cycle', 'priority')},
            },
        ),
    ]
