# Generated by Django 5.2.4 on 2026-08-09 12:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('preferences', '0003_preferredsection'),
        ('staff', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PreferredTimeSlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.CharField(choices=[('MONDAY', 'Monday'), ('TUESDAY', 'Tuesday'), ('WEDNESDAY', 'Wednesday'), ('THURSDAY', 'Thursday'), ('FRIDAY', 'Friday'), ('SATURDAY', 'Saturday')], max_length=10)),
                ('slot_number', models.PositiveSmallIntegerField()),
                ('priority', models.PositiveSmallIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('faculty', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='preferred_time_slots', to='staff.faculty')),
                ('preference_cycle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='preferred_time_slots', to='preferences.preferencecycle')),
            ],
            options={
                'ordering': ['faculty', 'priority'],
                'unique_together': {('faculty', 'preference_cycle', 'day', 'slot_number')},
            },
        ),
    ]
