# Generated by Django 5.2.4 on 2026-08-09 12:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('preferences', '0004_preferredtimeslot'),
        ('staff', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkloadPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('minimum_hours', models.PositiveSmallIntegerField(default=0)),
                ('preferred_hours', models.PositiveSmallIntegerField()),
                ('maximum_hours', models.PositiveSmallIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('faculty', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workload_preferences', to='staff.faculty')),
                ('preference_cycle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workload_preferences', to='preferences.preferencecycle')),
            ],
            options={
                'ordering': ['faculty'],
                'unique_together': {('faculty', 'preference_cycle')},
            },
        ),
    ]
