from django.db import models

from apps.academics.models import Section, SubjectOffering
from apps.staff.models import Faculty

from .allocation_run import AllocationRun


class SubjectAllocation(models.Model):
    """
    Represents the assignment of a faculty member to a subject offering
    generated by an allocation run.
    """

    class Status(models.TextChoices):
        PROPOSED = "PROPOSED", "Proposed"
        CONFIRMED = "CONFIRMED", "Confirmed"
        REJECTED = "REJECTED", "Rejected"
        MANUAL = "MANUAL", "Manual"

    class Day(models.TextChoices):
        MONDAY = "MONDAY", "Monday"
        TUESDAY = "TUESDAY", "Tuesday"
        WEDNESDAY = "WEDNESDAY", "Wednesday"
        THURSDAY = "THURSDAY", "Thursday"
        FRIDAY = "FRIDAY", "Friday"
        SATURDAY = "SATURDAY", "Saturday"

    allocation_run = models.ForeignKey(
        AllocationRun,
        on_delete=models.CASCADE,
        related_name="subject_allocations",
    )

    subject_offering = models.ForeignKey(
        SubjectOffering,
        on_delete=models.PROTECT,
        related_name="allocations",
    )

    faculty = models.ForeignKey(
        Faculty,
        on_delete=models.PROTECT,
        related_name="subject_allocations",
    )

    section = models.ForeignKey(
        Section,
        on_delete=models.PROTECT,
        related_name="subject_allocations",
    )

    day = models.CharField(
        max_length=10,
        choices=Day.choices,
    )

    slot_number = models.PositiveSmallIntegerField()

    status = models.CharField(
        max_length=20,
        choices=Status.choices,
        default=Status.PROPOSED,
    )

    preference_score = models.DecimalField(
        max_digits=6,
        decimal_places=2,
        default=0,
    )

    workload_hours = models.PositiveSmallIntegerField(
        default=0,
    )

    is_preference_matched = models.BooleanField(
        default=False,
    )

    is_conflict_free = models.BooleanField(
        default=True,
    )

    notes = models.TextField(
        blank=True,
    )

    created_at = models.DateTimeField(
        auto_now_add=True,
    )

    updated_at = models.DateTimeField(
        auto_now=True,
    )

    class Meta:
        ordering = [
            "allocation_run",
            "subject_offering",
            "section",
        ]

        unique_together = (
            "allocation_run",
            "subject_offering",
            "section",
        )

    def __str__(self):
        return (
            f"{self.subject_offering.subject.code} - "
            f"{self.section} - "
            f"{self.faculty.full_name} - "
            f"{self.day} Slot {self.slot_number}"
        )