import { useEffect, useState } from "react";
import { useNavigate, useParams } from "react-router-dom";

import allocationService from "../services/allocationService";

import "./AllocationResults.css";

function AllocationResults() {
  const { runId } = useParams();
  const navigate = useNavigate();

  const [allocations, setAllocations] = useState([]);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState("");

  useEffect(() => {
    loadAllocations();
  }, [runId]);

  const loadAllocations = async () => {
    setLoading(true);
    setError("");

    try {
      const data =
        await allocationService.getRunAllocations(runId);

      const allocationList = Array.isArray(data)
        ? data
        : data?.results || [];

      setAllocations(allocationList);
    } catch (err) {
      console.error(
        "Failed to load allocations:",
        err
      );

      if (err.response?.status === 401) {
        navigate("/login");
        return;
      }

      setError(
        "Unable to load allocation results."
      );
    } finally {
      setLoading(false);
    }
  };

  const getStatusClass = (status) => {
    return `allocation-status-${String(
      status || ""
    ).toLowerCase()}`;
  };

  return (
    <div className="allocation-results-page">

      <header className="allocation-header">

        <div>
          <h1>Allocation Results</h1>

          <p>
            Allocation Run #{runId}
          </p>
        </div>

        <button
          className="back-button"
          onClick={() => navigate("/dashboard")}
        >
          Back to Dashboard
        </button>

      </header>

      <main className="allocation-content">

        {error && (
          <div className="allocation-error">
            {error}
          </div>
        )}

        {loading ? (

          <div className="allocation-loading">
            Loading allocation results...
          </div>

        ) : allocations.length === 0 ? (

          <div className="allocation-empty">
            <h2>No allocations found</h2>

            <p>
              This allocation run does not contain
              any allocation records.
            </p>
          </div>

        ) : (

          <>
            <section className="allocation-summary">

              <div className="summary-card">
                <span>Total Allocations</span>

                <strong>
                  {allocations.length}
                </strong>
              </div>

              <div className="summary-card">
                <span>Preference Matches</span>

                <strong>
                  {
                    allocations.filter(
                      (allocation) =>
                        allocation.is_preference_matched
                    ).length
                  }
                </strong>
              </div>

              <div className="summary-card">
                <span>Conflict Free</span>

                <strong>
                  {
                    allocations.filter(
                      (allocation) =>
                        allocation.is_conflict_free
                    ).length
                  }
                </strong>
              </div>

            </section>

            <section className="allocation-table-section">

              <div className="section-title">

                <h2>Faculty Allocations</h2>

                <p>
                  Faculty assignments generated by
                  the allocation engine.
                </p>

              </div>

              <div className="table-container">

                <table className="allocation-table">

                  <thead>
                    <tr>
                      <th>Subject</th>
                      <th>Faculty</th>
                      <th>Section</th>
                      <th>Day</th>
                      <th>Slot</th>
                      <th>Preference</th>
                      <th>Workload</th>
                      <th>Status</th>
                    </tr>
                  </thead>

                  <tbody>

                    {allocations.map(
                      (allocation) => (

                        <tr key={allocation.id}>

                          <td>
                            <div className="subject-cell">

                              <strong>
                                {
                                  allocation.subject_code
                                }
                              </strong>

                              <span>
                                {
                                  allocation.subject_name
                                }
                              </span>

                            </div>
                          </td>

                          <td>
                            <strong>
                              {
                                allocation.faculty_name ||
                                `Faculty #${allocation.faculty}`
                              }
                            </strong>
                          </td>

                          <td>
                            {
                              allocation.section_name ||
                              `Section #${allocation.section}`
                            }
                          </td>

                          <td>
                            {
                              allocation.day || "-"
                            }
                          </td>

                          <td>
                            {
                              allocation.slot_number ??
                              "-"
                            }
                          </td>

                          <td>

                            <div className="preference-cell">

                              <strong>
                                {
                                  allocation.preference_score ??
                                  0
                                }
                              </strong>

                              {allocation.is_preference_matched && (
                                <span>
                                  Matched
                                </span>
                              )}

                            </div>

                          </td>

                          <td>
                            {
                              allocation.workload_hours ??
                              0
                            } hrs
                          </td>

                          <td>

                            <span
                              className={`allocation-status ${getStatusClass(
                                allocation.status
                              )}`}
                            >
                              {
                                allocation.status ||
                                "ALLOCATED"
                              }
                            </span>

                          </td>

                        </tr>

                      )
                    )}

                  </tbody>

                </table>

              </div>

            </section>
          </>

        )}

      </main>

    </div>
  );
}

export default AllocationResults;